#include<iostream>
#include<chrono>
#include<vector>
#include <fstream> // 用于文件读写
#include "NOISE\PerlinNoise.hpp"

int main() {
    // 1. 使用种子创建Perlin噪声生成器
    unsigned int seed = 1337; // 使用一个固定种子，方便每次生成同样的结果
    // unsigned int seed = std::chrono::high_resolution_clock::now().time_since_epoch().count();
    PerlinNoise perlin(seed);
    std::cout << "使用种子: " << seed << "\n";

    // 2. 定义生成的参数
    const int resolution = 64; // 我们将在一个 64x64x64 的立方体中采样
    const float frequency = 5.0f;    // 噪声频率，控制云朵特征的大小
    const float threshold = 0.5f;   // 密度阈值，只有大于此值的点才被认为是云的一部分

    const char* filename = "cloud_point_cloud.obj";
    std::ofstream obj_file(filename);

    if (!obj_file.is_open()) {
        std::cerr << "错误: 无法打开文件 " << filename << std::endl;
        return 1;
    }

    std::cout << "正在生成点云OBJ文件，分辨率 " << resolution << "^3 ...\n";

    // 写入OBJ文件头信息
    obj_file << "# Generated by Perlin Noise Point Cloud Generator\n";
    obj_file << "# Seed: " << seed << "\n";

    int point_count = 0;

    // 3. 遍历采样区域的每一个点
    for (int k = 0; k < resolution; ++k) {
        for (int j = 0; j < resolution; ++j) {
            for (int i = 0; i < resolution; ++i) {
                // a. 将整数格点坐标映射到 [0, 1] 区间，再乘以频率
                float x = static_cast<float>(i) / resolution * frequency;
                float y = static_cast<float>(j) / resolution * frequency;
                float z = static_cast<float>(k) / resolution * frequency;

                // b. 获取该点的噪声值
                // Perlin噪声输出范围约[-1,1]，我们先把它映射到[0,1]
                float noise_value = perlin.getValue(x, y, z);
                float density = (noise_value + 1.0f) / 2.0f; 

                // c. 如果密度大于阈值，就写入一个顶点
                if (density > threshold) {
                    // 为了让云居中显示，我们将坐标从 [0, resolution] 平移到 [-res/2, res/2]
                    float world_x = i - resolution / 2.0f;
                    float world_y = j - resolution / 2.0f;
                    float world_z = k - resolution / 2.0f;
                    
                    // OBJ格式中，一个顶点以 "v" 开头
                    obj_file << "v " << world_x << " " << world_y << " " << world_z << "\n";
                    point_count++;
                }
            }
        }
    }

    obj_file.close();
    std::cout << "生成完毕！共写入 " << point_count << " 个顶点到 " << filename << "\n";
    std::cout << "您现在可以用三维软件（如 Blender, MeshLab）打开这个文件查看了。\n";

    return 0;
}